### ISSUE TITLE
nvim lsp installer available ?

### ISSUE THREAD

**Issue by bboyadao** [mrjosh/helm-lint-ls#1]
Could you make it work with https://github.com/williamboman/nvim-lsp-installer ?

**Comment by mrjosh** [comment]
hey @bboyadao sorry for my late response

I gotta say, this project is still at development stage
so please expect some bugs here and there

I'll make it available on `nvim-lsp-installer` as soon as it gets to a stable version
but if you're using [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), which i believe you have it installed
you can follow these steps below to have it setup

## 1) Download the latest version of helm_lint_ls binary from [here](https://github.com/mrjosh/helm-lint-ls/releases)
* Move the binary to whatever location you want, just be aware that you need to put the binary path inside the config setup

## 2) Setup it at your nvim configuration file
```lua
local configs = require('lspconfig.configs')
local lspconfig = require('lspconfig')

if not configs.helm_lint_ls then
  configs.helm_lint_ls = {
    default_config = {
      cmd = {"{helm_lint_ls_binary_path}", "serve"},
      filetypes = {'helm'},
      root_dir = function(fname)
        return util.root_pattern('Chart.yaml', 'values.yaml')(fname)
      end,
    },
  }
end

lspconfig.helm_lint_ls.setup {}
```

## 3) Its done.
* Open a helm project with your neovim and see if you can see lsp attached the client to the buffer or not.
<img src="https://i.imgur.com/SrXotSk.png"/>

* If you're still having issues with this setup, feel free to ask. x

**Comment by varac** [comment]
[Just noticed](https://github.com/williamboman/nvim-lsp-installer) that:

> nvim-lsp-installer is no longer maintained.
> [mason.nvim](https://github.com/williamboman/mason.nvim) is the next generation version of nvim-lsp-installer.
